name: Rust Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build binary
        run: cargo build --release

      - name: Archive binary
        uses: actions/upload-artifact@v2
        with:
          name: my_binary
          path: target/release/my_binary

  download:
    runs-on: ubuntu-latest

    steps:
      - name: Download binary
        uses: actions/download-artifact@v2
        with:
          name: my_binary
          path: target/release/my_binary

      - name: Make binary available for download
        uses: actions/upload-artifact@v2
        with:
          name: my_binary
          path: target/release/my_binary