name: Rust Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build binary
        run: cargo build --release

      - name: Archive binary
        uses: actions/upload-artifact@v2
        with:
          name: IDS706_Fall2023_Project_2_Rust_CLI_with_SQLite
          path: target/release/IDS706_Fall2023_Project_2_Rust_CLI_with_SQLite